### ISSUE TITLE
Input integer as unsupported float or string

### ISSUE THREAD

**Issue by ppaawweeuu** [ladybug-tools/ladybug-blender#4]
Input integer as unsupported float or string

![data_types](https://user-images.githubusercontent.com/61344631/94489881-9a222680-01e5-11eb-98ff-ce342976bb5b.PNG)

**Comment by mostaphaRoudsari** [comment]
How does the nodes manage types? It looks like the input values that are typed in the node are considered as string instead of int/float values.

@Moult, do you enforce the types for inputs based on the types in the inputs that comes from the component JSON file? I'm not sure how all of this is handled here. 😀

**Comment by Moult** [comment]
Fixed in https://github.com/ladybug-tools/ladybug-blender/commit/7a411052e76b87770d07654f6f2bd453b525c505 - (whoops yes it's a typo in the commit message)

Yeah basically the nodes treat lists of everything as a string, so I had a casting function but I must've forgotten to implement it!

Should be fixed now :)

**Comment by ppaawweeuu** [comment]
Thx. I see change in generic_node.mustache file. Don't know how to use it.. (sorry, my limited skills). Do you plan to prepare next release with set of 'some_node.py' files?

**Comment by Moult** [comment]
Yes, the next release will contain the fix.

If you don't want to wait until the next release, go to `ADDONS_DIR/ladybug_tools/nodes/ladybug/` and open up the Python file in a text editor of the node that you're interested in, then look for these lines of code:

```
result = default if isinstance(value, str) and value == '' else value
        if result is None and data_type == 'bool':
            return False
```

You should insert the new lines of code as shown in green in the commit: https://github.com/ladybug-tools/ladybug-blender/commit/7a411052e76b87770d07654f6f2bd453b525c505

Then restart Blender and you should get the fix. If it's your first time editing code, be sure to keep a back up of the Python file in case you make a mistake!

**Comment by ppaawweeuu** [comment]
ok, works. thank you again.

**Comment by ppaawweeuu** [comment]
It would be nice to download next release, please ;)
with:
- sorted menu (with icons :) ;
- ready to read nodes (without stretching), with tooltips (i dont mind 'components' 'Rhino' etc, it is hard to read many jsons with /n and looooong lines);
- string/int/float/bool for inputs in every node;
- working edit source button.
@Moult , i think you have done huge step forward. Testing LB will be much, much easier!

btw - #nodevember is comming, there will be lot of b3d eyes watching noded stuff (not only shaders)

**Comment by Moult** [comment]
@ppaawweeuu you're correct. I just want to debug @seamoo 's issue first, just in case it is a showstopper bug for a release. Once that's done I'll do a new release.
