### ISSUE TITLE
LB Menu too long / UX

### ISSUE THREAD

**Issue by ppaawweeuu** [ladybug-tools/ladybug-blender#7]
LB Menu is difficult to use. Too long, not sorted, almost randomized. Hard to use & remember.

![menu](https://user-images.githubusercontent.com/61344631/94625672-9d86e200-02b9-11eb-9286-fafbac85d8a5.jpg)

**Comment by mostaphaRoudsari** [comment]
I agree that it is a long list. I don't know how to do it (or even if it is is possible to do) in Sverchok but Ladybug components are organized under sub-categories actually and we should be able to break them down in a similar manner.

![image](https://user-images.githubusercontent.com/2915573/94626714-a069de80-0289-11eb-8390-347a3b81e6a9.png)

For honeybee the list will be HUGE if not broken down into categories.

**Comment by Durman** [comment]
Probably can help https://github.com/nortikin/sverchok/pull/3477

**Comment by mostaphaRoudsari** [comment]
Hi @Durman, definitely does and I didn't know we can put the icons there! This is pretty awesome.

@Moult, what will you need from us to be able to add the icons? The information for tabs is already there. We can export the icons with each component when generating the JSON files.

**Comment by Moult** [comment]
Wow @Durman - ping @portnov there is quite a lot of magic in that PR happening. I'd like to avoid all the dynamic creation that's happening with the whole `index.md` thing and class factories. Can you perhaps show me a simple minimal code example of a submenu that is explicitly defined, but still uses the Sverchok menu classes so that later on I can specify icons and ensure that it shows in the tools panel / alt-space search seamlessly? I did try looking through the PR code and I gave up after a while - it might be easier if you gave me some hints :) I'm currently using the same approach that the sverchok-extra repo uses: https://github.com/ladybug-tools/ladybug-blender/blob/master/ladybug_tools/__init__.py#L31

@mostaphaRoudsari if you could provide a directory of icons as well as a filename reference somewhere in the JSON I think I can work something out :)

**Comment by portnov** [comment]
We do not have a single universal mechanism for all menus at the moment. Sverchok parses index.md; Sverchok-Extra has hardcoded list of nodes. Probably you'll have to read `menu.py` to understand what's going on. The code is not simple, for two reasons
1) it was not designed for easy extension, instead it evolved historically;
2) order of registration of addons at blender startup is undefined; that's why we have to have sort-of-callback mechanism with "extra category providers" to show categories from other addons.
If you have more specific questions, feel free to ask. Maybe @Durman  or @zeffii will be able to help too.

**Comment by mostaphaRoudsari** [comment]
@Moult, I added a new step to the export component to generate the icons alongside the JSON files. I didn't put the information into the JSON file as that takes some more thinking but the name of each icon is the same as the name of the JSON file.

Once this PR is merged you can get them from ladybug-grasshopper:

https://github.com/ladybug-tools/ladybug-grasshopper/pull/106

Meanwhile they are available under my fork of the repository:

https://github.com/mostaphaRoudsari/ladybug-grasshopper/tree/master/ladybug_grasshopper/icon

**Comment by chriswmackey** [comment]
ladybug-grasshopper PR has been merged. I'll start working on exporting the icons for the other Ladybug Tools Grasshopper plugin repos.

**Comment by Moult** [comment]
I hacked together something but I'm not quite sure if I did it right. A few questions I hope you can clarify:

 1. @portnov - in your PR https://github.com/nortikin/sverchok/pull/3477/files#diff-2dc7b7928c7443177fcb43886c13c7ffR102-R108 - it checks `is_submenu_call(bl_idname)`. When the value of `bl_idname` is `@ Foo`, what is the original class that provides the `bl_idname`? Is it a `SverchNodeItem`? Or a `SverchSeparator`? Or something else entirely?

 2. @vicdoval - in your PR https://github.com/nortikin/sverchok/pull/3582/files#diff-848c282d07ef88a9e90121bb50795ed6R100-R106 - how does this gather extra nodes accommodate submenus? (This perhaps relates to my first question) Unless, you expect the list to be flattened such that all submenu nodes are not nested?

**Comment by portnov** [comment]
Sverchok reads `index.md`, and expects it to be a list of node bl_idnames of nodes, for each category. But if some line starts with `@` then it is not actually a bl_idname, but an instruction to insert submenu. So, answering to your question, `bl_idname` in this situation is just a line which was read from `index.md`.

**Comment by Moult** [comment]
@portnov hmm, then if it is just a string, then I think this needs to be modified:

https://github.com/nortikin/sverchok/blob/c2ee0f14a34d506bf0ad0df4df29f67408e48570/ui/nodeview_space_menu.py#L274-L275

Currently for the extra categories menu, as you see on L275, it passes nodes, and on L274, nodes can't just be a string, it has to be an object which has a `nodetype` attribute.

Perhaps that code needs to be modified to allow extra categories to have submenus (i.e. to simply pass in a string to indicate it is a submenu)?

**Comment by portnov** [comment]
Yes, as far as I see, submenus in extra-categories are not supported currently. I'm not sure how it would be more convenient - to pass a string instead of node, or to pass a SverchCategory instead of NodeItem, or whatever. PR would be welcome :)

**Comment by Moult** [comment]
@portnov cool :) So I'm not going crazy ;) I tried with SverchCategory, but in the alt-space menu it calls get_node_class() and gets upset there, so although I can introduce even more hacks over it, there must be a better solution.

I'll see if I can pull together a PR for passing in a string.

**Comment by portnov** [comment]
The thing is, "main" categories are read from `index.md`, but where exactly "extra_categories" come from — Sverchok does not know. So, I think, it should expect that "extra" addon would somehow prepare the whole tree as Python object, maybe as a list of SverchCategory, or maybe a special class that would allow nesting... So that it should be responsibility of "extra" addon to read it's categories from wherever and build the menu tree; Sverchok should just display the tree.

**Comment by Moult** [comment]
@portnov agree that would be even better - let the extras build whatever menus, and Sverchok just displays an entry point - after which the extras takes over.

**Comment by Moult** [comment]
I did a proof of concept that shows submenus with the latter solution: no magic and no need to patch Sverchok core - all menu classes defined in the extras repo, no menu generation in core. Works well! (I think I need to check the `T` menu still, but should be straightforward). Thanks for all the help @portnov!

@vicdoval no need to answer my previous question, as that was based on my prior incorrect understanding that it was expecting an object. All clear now :)

![2020-10-02-180612_714x99_scrot](https://user-images.githubusercontent.com/88302/94901467-0a78c280-04da-11eb-9654-dea4e3a73256.png)

Will find some time to patch up the generator finally close this bug :) It's been a fun tour of the codebase!

**Comment by Moult** [comment]
Funky. I now run an imagemagick command to invert colour intensities so that it shows well against dark themes, which might've lead to a couple funky colours here and there but overall I think it works well! Bug closed!

![2020-10-03-141500_452x205_scrot](https://user-images.githubusercontent.com/88302/94983097-f937c080-0582-11eb-91be-8f16865b4164.png)
![2020-10-03-141453_423x240_scrot](https://user-images.githubusercontent.com/88302/94983098-fa68ed80-0582-11eb-8874-f7eff83abfc5.png)
![2020-10-03-141447_479x409_scrot](https://user-images.githubusercontent.com/88302/94983099-fb018400-0582-11eb-84e8-37a7731406ef.png)
![2020-10-03-141440_433x351_scrot](https://user-images.githubusercontent.com/88302/94983101-fb018400-0582-11eb-8c18-09e54508baff.png)
![2020-10-03-141433_669x623_scrot](https://user-images.githubusercontent.com/88302/94983102-fb9a1a80-0582-11eb-82c7-f1ec954c8a72.png)
![2020-10-03-141423_639x159_scrot](https://user-images.githubusercontent.com/88302/94983103-fc32b100-0582-11eb-9083-908d4be4f2bd.png)
![2020-10-03-141905_372x445_scrot](https://user-images.githubusercontent.com/88302/94983168-6a777380-0583-11eb-9e53-1528eda22b98.png)
